version: "3.9"

services:
  comunicationManagement-service:
    build:
      context: ./src
    ports:
      - "80:5000"
    restart: always
    networks:
      - nodejs-network

networks:
  nodejs-network:
    driver: bridge
